<?php

namespace ITHilbert\LaravelKit\Jobs\Ai;

use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class RunGeminiTaskJob extends AbstractAiJob
{
    protected function getJobType(): string
    {
        return 'gemini_worker';
    }

    public function handle()
    {
        $run = $this->getRunLog();
        $run->update(['status' => 'processing']);
        $this->aiTask->update(['status' => 'running']);

        try {
            // Wir lassen die Anlage der Datei nur noch als Archiv/Log, aber forcieren den Agent nicht mehr, sie selbst zu lesen!
            // (Umgeht Problem 1: File ignored by configure ignore patterns bei storage/* Dateien)
            $taskFile = storage_path('app/ai_tasks/task_'.$this->aiTask->id.'.md');
            if (! file_exists(dirname($taskFile))) {
                mkdir(dirname($taskFile), 0755, true);
            }

            $content = "# Task #{$this->aiTask->id}: {$this->aiTask->title}\n\n";
            $content .= "## Module: {$this->aiTask->module}\n\n";
            $content .= "## Instructions\n{$this->aiTask->description}\n\n";
            $content .= "---\n";
            $content .= "*Auto-generated by AI Pipeline.*\n\n";
            file_put_contents($taskFile, $content);

            $agentPath = base_path('node_modules/.bin/gemini');
            if (! file_exists($agentPath)) {
                throw new \Exception("gemini-cli ist nicht installiert. Bitte 'npm install @google/gemini-cli -D' in ".base_path().' ausführen.');
            }

            $prompt = "Modul: {$this->aiTask->module}\n";
            $prompt .= "Arbeitsauftrag / Task:\n" . $this->aiTask->description . "\n\n";
            $prompt .= "WICHTIGE REGEL: Du befindest dich in einer vollautomatisierten Pipeline ohne User-Interaktion!\n";
            $prompt .= "- Führe keine Dialoge und stelle keine Fragen.\n";
            $prompt .= "- Aktiviere unter keinen Umständen den Planning Mode.\n";
            $prompt .= "- Warte auf KEIN User-Okay, sondern setze alle Schritte blind um.\n";
            $prompt .= "- Falls eine Rückfrage/Klarstellung absolut zwingend ist, nutze den Block '# FEEDBACK_REQUIRED' und stelle dort deine Frage. Beende danach den Task.\n";
            $prompt .= "- Zusatzanweisung: Hänge an deine finale System-Ausgabe ganz unten einen Abschnitt '# Agent Feedback' an. Beschreibe darin kurz: Wo lagen die Probleme? Wie lang dauerte die Suche & das Coden?\n";
            $prompt .= "- Beende dich bei Erfolg einfach mit Errorcode 0.";

            $processArgs = [
                $agentPath,
                '--yolo',
                '-p',
                $prompt,
            ];

            // Workspace-Erweiterung für Pakete (Symlinks im Vendor, damit die Bearbeitung per replace nicht blockiert wird)
            $ithilbertVendor = base_path('vendor/ithilbert');
            if (is_dir($ithilbertVendor)) {
                foreach (scandir($ithilbertVendor) as $pkg) {
                    if ($pkg !== '.' && $pkg !== '..') {
                        $pkgPath = $ithilbertVendor . '/' . $pkg;
                        if (is_link($pkgPath)) {
                            $realPath = realpath($pkgPath);
                            if ($realPath) {
                                $processArgs[] = '--include-directories';
                                $processArgs[] = $realPath;
                            }
                        }
                    }
                }
            }

            $process = new Process($processArgs);

            $process->setWorkingDirectory(base_path());
            $process->setTimeout(3600);

            // Environment Variablen injecten (Auth)
            $env = $_ENV;
            $env['GOOGLE_API_KEY'] = config('services.gemini.key', env('GEMINI_API_KEY'));
            $process->setEnv($env);

            // Wenn der Agent Terminal Colors / PTY braucht.
            // Ohne PTY für gemini json output vermutlich sicherer, aber wir lassen es erstmal false.
            $process->setPty(false);

            $startTime = microtime(true);
            $output = '';
            $errorOutput = '';
            
            $process->run(function ($type, $buffer) use (&$output, &$errorOutput, $startTime) {
                $elapsed = round(microtime(true) - $startTime, 1);
                $lines = explode("\n", rtrim($buffer, "\n"));
                
                if ($type === Process::ERR) {
                    foreach ($lines as $line) {
                        $errorOutput .= "[+{$elapsed}s] " . $line . "\n";
                    }
                } else {
                    $output .= $buffer;
                }
            });

            if (! $process->isSuccessful()) {
                throw new ProcessFailedException($process);
            }
            
            $finalLog = trim($output);
            
            // Falls stderr Logs (Tracing, Zeiten etc.) enthalten sind, unten anhängen oder kombinieren
            if (!empty($errorOutput)) {
                $finalLog .= "\n\n--- CLI LOGS (Stderr) ---\n" . trim($errorOutput);
            }
            
            // Checken, falls die CLI (z.B. durch andere Configs) doch noch JSON geliefert hat
            $decoded = json_decode($output, true);
            if (json_last_error() === JSON_ERROR_NONE && isset($decoded['response'])) {
                $finalLog = "Gemini Response:\n".$decoded['response'];
                if (!empty($errorOutput)) {
                    $finalLog .= "\n\n--- CLI LOGS (Stderr) ---\n" . trim($errorOutput);
                }
            }


            // Check for feedback required
            $rueckfrage = null;
            if (preg_match('/# FEEDBACK_REQUIRED\s*(.*?)($|# Agent Feedback)/s', $finalLog, $matches)) {
                $rueckfrage = trim($matches[1]);
            }

            $totalTime = round(microtime(true) - $startTime, 1);
            $run->update([
                'status' => $rueckfrage ? 'needs_info' : 'success',
                'stdout_log' => "Gemini CLI wurde in {$totalTime}s ausgeführt!\n\n"
                              . "--- URSPRÜNGLICHE AUFGABE ---\n"
                              . trim($this->aiTask->description) . "\n\n"
                              . "--- OUTPUT ---\n"
                              . $finalLog,
                'stderr_log' => null,
                'finished_at' => now(),
            ]);

            if ($rueckfrage) {
                $this->aiTask->update([
                    'status' => 'needs_info',
                    'rueckfrage' => $rueckfrage,
                ]);
            } else {
                $this->aiTask->update([
                    'status' => 'completed',
                ]);
            }

        } catch (\Exception $e) {
            $run->update([
                'status' => 'failed',
                'stderr_log' => $e->getMessage(),
                'finished_at' => now(),
            ]);
            $this->aiTask->update(['status' => 'failed']);
            $this->fail($e);
        }
    }
}
