<?php

namespace ITHilbert\LaravelKit\Strategies;

use Closure;
use Illuminate\Support\Facades\Process;
use ITHilbert\LaravelKit\Contracts\AiExecutionStrategy;

class SingleRunStrategy implements AiExecutionStrategy
{
    public function execute($aiTask, $run, Closure $failClosure)
    {
        $run->update(['status' => 'processing']);
        $aiTask->update(['status' => 'running']);

        try {
            // Wir lassen die Anlage der Datei nur noch als Archiv/Log, aber forcieren den Agent nicht mehr, sie selbst zu lesen!
            $taskFile = storage_path('app/ai_tasks/task_'.$aiTask->id.'.md');
            if (! file_exists(dirname($taskFile))) {
                mkdir(dirname($taskFile), 0755, true);
            }

            $content = "# Task #{$aiTask->id}: {$aiTask->title}\n\n";
            $content .= "## Module: {$aiTask->module}\n\n";
            $content .= "## Instructions\n{$aiTask->description}\n\n";
            $content .= "---\n";
            $content .= "*Auto-generated by AI Pipeline.*\n\n";
            file_put_contents($taskFile, $content);

            $agentPath = base_path('node_modules/.bin/gemini');
            if (! file_exists($agentPath)) {
                throw new \Exception("gemini-cli ist nicht installiert. Bitte 'npm install @google/gemini-cli -D' in ".base_path().' ausführen.');
            }

            $prompt = "Modul: {$aiTask->module}\n";
            $prompt .= "Arbeitsauftrag / Task:\n" . $aiTask->description . "\n\n";
            $prompt .= "WICHTIGE REGEL: Du befindest dich in einer vollautomatisierten Pipeline ohne User-Interaktion!\n";
            $prompt .= "- Führe keine Dialoge und stelle keine Fragen.\n";
            $prompt .= "- Aktiviere unter keinen Umständen den Planning Mode.\n";
            $prompt .= "- Warte auf KEIN User-Okay, sondern setze alle Schritte blind um.\n";
            $prompt .= "- Falls eine Rückfrage/Klarstellung absolut zwingend ist, nutze den Block '# FEEDBACK_REQUIRED' und stelle dort deine Frage. Beende danach den Task.\n";
            $prompt .= "- Zusatzanweisung: Hänge an deine finale System-Ausgabe ganz unten einen Abschnitt '# Agent Feedback' an. Beschreibe darin kurz: Wo lagen die Probleme? Wie lang dauerte die Suche & das Coden?\n";
            $prompt .= "- Beende dich bei Erfolg einfach mit Errorcode 0.";

            $processArgs = [
                $agentPath,
                '--yolo',
                '-p',
                $prompt,
            ];

            // Workspace-Erweiterung für Pakete: Wir binden nur noch selektiv ein, um den Gemini-Context extrem zu verkleinern!
            $ithilbertVendor = base_path('vendor/ithilbert');
            $targetPkg = strtolower($aiTask->module);
            
            // Map common modules to the laravel-kit package just in case
            if (in_array(strtolower($aiTask->module), ['ai', 'dashboard', 'core', 'laravel-kit'])) {
                $targetPkg = 'laravel-kit';
            }

            if (is_dir($ithilbertVendor)) {
                foreach (scandir($ithilbertVendor) as $pkg) {
                    if ($pkg !== '.' && $pkg !== '..') {
                        $pkgPath = $ithilbertVendor . '/' . $pkg;
                        
                        // Nur das konkrete Modul-Paket einbinden, um nicht zig MB Quellcode bei jedem Request hochzuladen
                        if ($pkg !== $targetPkg && $targetPkg !== 'all') {
                            continue;
                        }

                        if (is_link($pkgPath)) {
                            $realPath = realpath($pkgPath);
                            if ($realPath) {
                                $processArgs[] = '--include-directories';
                                $processArgs[] = $realPath;
                            }
                        }
                    }
                }
            }

            // Environment Variablen injecten (Auth)
            $env = $_ENV;
            $env['GOOGLE_API_KEY'] = config('services.gemini.key', env('GEMINI_API_KEY'));
            
            // Verhindern, dass die gemini-cli "Both GOOGLE_API_KEY and GEMINI_API_KEY are set" meckert
            if (isset($env['GEMINI_API_KEY'])) {
                unset($env['GEMINI_API_KEY']);
            }

            $startTime = microtime(true);
            $output = '';
            $errorOutput = '';
            
            $result = Process::path(base_path())
                ->timeout(3600)
                ->env($env)
                ->run($processArgs, function (string $type, string $buffer) use (&$output, &$errorOutput, $startTime) {
                    $elapsed = round(microtime(true) - $startTime, 1);
                    $lines = explode("\n", rtrim($buffer, "\n"));
                    
                    if ($type === 'err') {
                        foreach ($lines as $line) {
                            $errorOutput .= "[+{$elapsed}s] " . $line . "\n";
                        }
                    } else {
                        $output .= $buffer;
                    }
                });

            if (! $result->successful()) {
                throw new \Exception("ProcessFailed:\n" . $errorOutput);
            }
            
            $finalLog = trim($output) ?: trim($result->output());
            
            $finalError = trim($errorOutput) ?: trim($result->errorOutput());
            if (!empty($finalError)) {
                $finalLog .= "\n\n--- CLI LOGS (Stderr) ---\n" . $finalError;
            }
            
            // Checken, falls die CLI (z.B. durch andere Configs) doch noch JSON geliefert hat
            $decoded = json_decode($output, true);
            if (json_last_error() === JSON_ERROR_NONE && isset($decoded['response'])) {
                $finalLog = "Gemini Response:\n".$decoded['response'];
                if (!empty($errorOutput)) {
                    $finalLog .= "\n\n--- CLI LOGS (Stderr) ---\n" . trim($errorOutput);
                }
            }


            // Check for feedback required
            $rueckfrage = null;
            if (preg_match('/# FEEDBACK_REQUIRED\s*(.*?)($|# Agent Feedback)/s', $finalLog, $matches)) {
                $rueckfrage = trim($matches[1]);
            }

            $totalTime = round(microtime(true) - $startTime, 1);
            $run->update([
                'status' => $rueckfrage ? 'needs_info' : 'success',
                'stdout_log' => "Gemini CLI wurde in {$totalTime}s ausgeführt (SingleRunStrategy)!\n\n"
                              . "--- URSPRÜNGLICHE AUFGABE ---\n"
                              . trim($aiTask->description) . "\n\n"
                              . "--- OUTPUT ---\n"
                              . $finalLog,
                'stderr_log' => null,
                'finished_at' => now(),
            ]);

            if ($rueckfrage) {
                $aiTask->update([
                    'status' => 'needs_info',
                    'rueckfrage' => $rueckfrage,
                ]);
            } else {
                $aiTask->update([
                    'status' => 'completed',
                ]);
            }

        } catch (\Exception $e) {
            $run->update([
                'status' => 'failed',
                'stderr_log' => $e->getMessage(),
                'finished_at' => now(),
            ]);
            $aiTask->update(['status' => 'failed']);
            $failClosure($e);
        }
    }
}
